<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Tenant extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'uuid',
        'client_id',
        'business_name',
        'slug',
        'domain',
        'email',
        'phone',
        'emergency_contact',
        'country',
        'region',
        'city',
        'address',
        'postal_code',
        'business_type',
        'preferred_payment_method',
        'status',
        'trial_starts_at',
        'trial_ends_at',
        'subscribed_at',
        'subscription_ends_at',
        'cancelled_at',
        'max_users',
        'max_stores',
        'max_products',
        'current_users_count',
        'current_stores_count',
        'current_products_count',
        'settings',
        'metadata',
    ];

    protected $casts = [
        'trial_starts_at' => 'datetime',
        'trial_ends_at' => 'datetime',
        'subscribed_at' => 'datetime',
        'subscription_ends_at' => 'datetime',
        'cancelled_at' => 'datetime',
        'settings' => 'array',
        'metadata' => 'array',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($tenant) {
            // Auto-generate UUID
            if (!$tenant->uuid) {
                $tenant->uuid = (string) Str::uuid();
            }
            
            // Auto-generate slug from business name
            if (!$tenant->slug) {
                $tenant->slug = Str::slug($tenant->business_name);
            }
            
            // Client ID is auto-generated by database trigger
        });
    }

    // Relationships
    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function roles()
    {
        return $this->hasMany(Role::class);
    }

    // Helper methods
    public function isOnTrial(): bool
    {
        return $this->status === 'trial' && 
               $this->trial_ends_at && 
               $this->trial_ends_at->isFuture();
    }

    public function isActive(): bool
    {
        return in_array($this->status, ['trial', 'active']);
    }

    public function hasReachedUserLimit(): bool
    {
        return $this->current_users_count >= $this->max_users;
    }

    public function hasReachedStoreLimit(): bool
    {
        return $this->current_stores_count >= $this->max_stores;
    }

    public function hasReachedProductLimit(): bool
    {
        return $this->current_products_count >= $this->max_products;
    }

    // Route model binding key
    public function getRouteKeyName()
    {
        return 'client_id';
    }
}